name: Verify App
on:
  push:
    branches:
      - main
  pull_request:

env:
  APOLLO_TELEMETRY_DISABLED: 1

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0
      - uses: actions/setup-node@v3.0.0
        with:
          node-version: "16"
          cache: "yarn"
      - run: yarn install --frozen-lockfile --prefer-offline
      - name: Prettier
        run: yarn fmt:ci
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0
      - uses: actions/setup-node@v3.0.0
        with:
          node-version: "16"
          cache: "yarn"
      - run: yarn install --frozen-lockfile --prefer-offline
      - name: Build folder does not exist
        run: test ! -d gateway/dist
      - name: Build
        run: yarn build
      - name: Check build
        run: test -d gateway/dist
